# Ha éles szerverre tenném ki a programot, akkor létrehoznék egy deploy branch-et

name: CI Pipeline

on:
  push:

    branches: [ "deploy" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Backend Docker image
      run: docker build -t kerteszbence/cicd-pipeline-backend backend/
    - name: Backend image push to Dockerhub
      run: docker push kerteszbence/cicd-pipeline-backend:latest

# ha lenne frontend

    - name: Build the Frontend Docker image
      run: docker build -t kerteszbence/cicd-pipeline-frontend frontend/
    - name: Frontend image push to Dockerhub
      run: docker push kerteszbence/cicd-pipeline-frontend:latest
